{
  "compatibilityLevel": 1601,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.137.1102.0 (24.10)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Dataset\",\"StartDate\",\"EndDate\",\"DimDate\",\"_Measures\"]"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "Entities": {
              "dataset": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Dataset"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "dataset": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "dataset.brand": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Dataset",
                    "ConceptualProperty": "Brands"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "brand": {
                      "State": "Generated"
                    }
                  },
                  {
                    "product": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "variety": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "marque": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "make": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "kind": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "trademark": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "type": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "style": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "class": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "strain": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  }
                ],
                "Visibility": {
                  "Value": "Hidden"
                }
              },
              "dataset.brand1": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Dataset",
                    "ConceptualProperty": "Brand"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "brand": {
                      "State": "Generated"
                    }
                  },
                  {
                    "product": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "variety": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "marque": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "make": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "kind": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "trademark": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "type": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "style": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "class": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "strain": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  }
                ],
                "Visibility": {
                  "Value": "Hidden"
                }
              },
              "dataset.month": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Dataset",
                    "ConceptualProperty": "Month"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "month": {
                      "State": "Generated"
                    }
                  },
                  {
                    "date": {
                      "State": "Generated",
                      "Weight": 0.7
                    }
                  },
                  {
                    "mth": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  }
                ]
              },
              "dataset.placement": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Dataset",
                    "ConceptualProperty": "Placement"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "placement": {
                      "State": "Generated"
                    }
                  },
                  {
                    "assignment": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "location": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "settlement": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "situation": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "appointment": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "engagement": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "residency": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "employment": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "post": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "position": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  }
                ]
              },
              "dataset.placement_bucket": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Dataset",
                    "ConceptualProperty": "Placement_Bucket"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "placement bucket": {
                      "State": "Generated"
                    }
                  },
                  {
                    "Placement_Bucket": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "bucket": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "placement pail": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "placement container": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "placement vessel": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "pail": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "container": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "vessel": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  }
                ]
              },
              "dataset.projection": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Dataset",
                    "ConceptualProperty": "Projection"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "projection": {
                      "State": "Generated"
                    }
                  },
                  {
                    "prognosis": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "prediction": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "prognostication": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "forecast": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "plan": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "estimate": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "protuberance": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.466
                    }
                  },
                  {
                    "protrusion": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.466
                    }
                  },
                  {
                    "ledge": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.466
                    }
                  },
                  {
                    "outcrop": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.452
                    }
                  }
                ]
              },
              "dataset.sl__no_": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Dataset",
                    "ConceptualProperty": "Sl. No."
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "sl. no.": {
                      "State": "Generated"
                    }
                  },
                  {
                    "sl. number .": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.599
                    }
                  }
                ]
              },
              "dataset.team_leader": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Dataset",
                    "ConceptualProperty": "Team Leader"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "team leader": {
                      "State": "Generated"
                    }
                  },
                  {
                    "leader": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "team frontrunner": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "team trailblazer": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "team groundbreaker": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "team forerunner": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "frontrunner": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "trailblazer": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "groundbreaker": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "forerunner": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "team front-runner": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "team spearhead": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  }
                ]
              },
              "dim_date": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "DimDate"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "dim date": {
                      "State": "Generated"
                    }
                  },
                  {
                    "DimDate": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "dim moment": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "dim period": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  }
                ]
              },
              "dim_date.date": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "DimDate",
                    "ConceptualProperty": "Dates"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "date": {
                      "State": "Generated"
                    }
                  },
                  {
                    "moment": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "period": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  }
                ]
              },
              "dim_date.month": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "DimDate",
                    "ConceptualProperty": "Month"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "month": {
                      "State": "Generated"
                    }
                  },
                  {
                    "mth": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  }
                ]
              },
              "dim_date.month_name": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "DimDate",
                    "ConceptualProperty": "Month Name"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "month name": {
                      "State": "Generated"
                    }
                  },
                  {
                    "month nickname": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "month title": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "month label": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "month tag": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "mth name": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  }
                ]
              },
              "dim_date.quarter": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "DimDate",
                    "ConceptualProperty": "Quarter"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "quarter": {
                      "State": "Generated"
                    }
                  },
                  {
                    "qtr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.818
                    }
                  }
                ]
              },
              "dim_date.quarter_name": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "DimDate",
                    "ConceptualProperty": "Quarter Name"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "quarter name": {
                      "State": "Generated"
                    }
                  },
                  {
                    "quarter nickname": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "quarter title": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "quarter label": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "quarter tag": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "qtr name": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.667
                    }
                  }
                ]
              },
              "dim_date.week_name": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "DimDate",
                    "ConceptualProperty": "Week Name"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "week name": {
                      "State": "Generated"
                    }
                  },
                  {
                    "week nickname": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "week title": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "week label": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "week tag": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  }
                ]
              },
              "dim_date.week_of_year": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "DimDate",
                    "ConceptualProperty": "Week of Year"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "week of year": {
                      "State": "Generated"
                    }
                  },
                  {
                    "week of yr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.609
                    }
                  }
                ]
              },
              "dim_date.year": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "DimDate",
                    "ConceptualProperty": "Year"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "year": {
                      "State": "Generated"
                    }
                  },
                  {
                    "yr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  }
                ]
              },
              "parameter": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Parameter"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "parameter": {
                      "State": "Generated",
                      "Weight": 0.87
                    }
                  },
                  {
                    "stricture": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "limitation": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "restriction": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "constraint": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "consideration": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "boundary": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "limit": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "bound": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "factor": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "issue": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  }
                ]
              },
              "parameter.parameter": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Parameter",
                    "ConceptualProperty": "Parameter"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "parameter": {
                      "State": "Generated"
                    }
                  },
                  {
                    "stricture": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "limitation": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "restriction": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "constraint": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "consideration": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "boundary": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "limit": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "bound": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "factor": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "issue": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  }
                ]
              },
              "parameter.parameter_value": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Parameter",
                    "ConceptualProperty": "Parameter Value"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "parameter value": {
                      "State": "Generated"
                    }
                  },
                  {
                    "value": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "parameter assessment": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "assessment": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "parameter worth": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "parameter price": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "parameter cost": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "parameter charge": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "parameter rate": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "worth": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "price": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "cost": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  }
                ]
              },
              "pseudo_prod_table": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Pseudo Prod Table"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "pseudo prod table": {
                      "State": "Generated"
                    }
                  },
                  {
                    "prod table": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "pseudo prod tabletop": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.508
                    }
                  },
                  {
                    "prod tabletop": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "pseudo prod bench": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.492
                    }
                  },
                  {
                    "pseudo prod board": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.492
                    }
                  },
                  {
                    "pseudo prod counter": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.492
                    }
                  },
                  {
                    "pseudo prod stand": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.492
                    }
                  },
                  {
                    "pseudo prod slab": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.492
                    }
                  },
                  {
                    "pseudo prod desk": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.492
                    }
                  },
                  {
                    "pseudo prod stall": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.492
                    }
                  },
                  {
                    "pseudo prod table top": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.492
                    }
                  }
                ]
              },
              "pseudo_prod_table.brand": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Pseudo Prod Table",
                    "ConceptualProperty": "Brand"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "brand": {
                      "State": "Generated"
                    }
                  },
                  {
                    "product": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "variety": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "marque": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "make": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "kind": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "trademark": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "type": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "style": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "class": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "strain": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  }
                ]
              },
              "pseudo_prod_table_b": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Pseudo Prod Table B"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "pseudo prod table b": {
                      "State": "Generated"
                    }
                  },
                  {
                    "b": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "table b": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "prod table b": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  }
                ]
              },
              "pseudo_prod_table_b.brand": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Pseudo Prod Table B",
                    "ConceptualProperty": "Brands"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "brand": {
                      "State": "Generated"
                    }
                  },
                  {
                    "product": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "variety": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "marque": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "make": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "kind": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "trademark": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "type": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "style": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "class": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "strain": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  }
                ]
              },
              "v_Measures_measure": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Measures"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "_measure": {
                      "State": "Generated"
                    }
                  },
                  {
                    "_ degree": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "_ quantity": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "_ quota": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "_ extent": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "_ amount": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "_ portion": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "_ ration": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "_ size": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  }
                ]
              },
              "v_Measures_measure.bar": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Measures",
                    "ConceptualProperty": "Bar"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "bar": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "v_Measures_measure.bar_chart_detail": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Measures",
                    "ConceptualProperty": "Bar Chart Detail"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "bar chart detail": {
                      "State": "Generated"
                    }
                  },
                  {
                    "detail": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "chart detail": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "bar chart aspect": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.508
                    }
                  },
                  {
                    "bar chart element": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.508
                    }
                  },
                  {
                    "bar chart fact": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.508
                    }
                  },
                  {
                    "chart aspect": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "chart element": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "chart fact": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "bar diagram detail": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.492
                    }
                  },
                  {
                    "bar plan detail": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.492
                    }
                  },
                  {
                    "bar chart part": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.492
                    }
                  },
                  {
                    "bar chart feature": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.492
                    }
                  }
                ]
              },
              "v_Measures_measure.bottom_brands_placement": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Measures",
                    "ConceptualProperty": "Bottom Brands Placement"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "bottom brands placement": {
                      "State": "Generated"
                    }
                  },
                  {
                    "brands placement": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "bottom brand assignment": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.508
                    }
                  },
                  {
                    "bottom brand location": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.508
                    }
                  },
                  {
                    "bottom brand settlement": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.508
                    }
                  },
                  {
                    "bottom brand situation": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.508
                    }
                  },
                  {
                    "bottom brand appointment": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.508
                    }
                  },
                  {
                    "bottom brand engagement": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.508
                    }
                  },
                  {
                    "bottom brand residency": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.508
                    }
                  },
                  {
                    "brand assignment": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "brand location": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "brand settlement": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "Order Placement Qty": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "v_Measures_measure.bottom_brands_total": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Measures",
                    "ConceptualProperty": "Bottom Brands Total"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "bottom brands total": {
                      "State": "Generated"
                    }
                  },
                  {
                    "brands total": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "bottom brand aggregate": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.739
                    }
                  },
                  {
                    "bottom brand overall": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.739
                    }
                  },
                  {
                    "brand aggregate": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "brand overall": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  }
                ]
              },
              "v_Measures_measure.customer_rank": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Measures",
                    "ConceptualProperty": "Customer Rank"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "customer rank": {
                      "State": "Generated"
                    }
                  },
                  {
                    "client rank": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "consumer rank": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "user rank": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "buyer rank": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "patron rank": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "purchaser rank": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "shopper rank": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  }
                ]
              },
              "v_Measures_measure.customers_top_n_sum": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Measures",
                    "ConceptualProperty": "Customers top N Sum"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "customers top n sum": {
                      "State": "Generated"
                    }
                  },
                  {
                    "n sum": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "customer top n summation": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.771
                    }
                  },
                  {
                    "customer top n aggregation": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.771
                    }
                  },
                  {
                    "n summation": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "n aggregation": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "customer top n total": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.748
                    }
                  },
                  {
                    "customer top n aggregate": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.748
                    }
                  },
                  {
                    "customer top n amount": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.748
                    }
                  },
                  {
                    "n total": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "n aggregate": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "n amount": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  }
                ]
              },
              "v_Measures_measure.guge_high_value": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Measures",
                    "ConceptualProperty": "Guge High Value"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "guge high value": {
                      "State": "Generated"
                    }
                  },
                  {
                    "guge high assessment": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.508
                    }
                  },
                  {
                    "guge high worth": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.492
                    }
                  },
                  {
                    "guge high price": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.492
                    }
                  },
                  {
                    "guge high cost": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.492
                    }
                  },
                  {
                    "guge high charge": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.492
                    }
                  },
                  {
                    "guge high rate": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.492
                    }
                  },
                  {
                    "guge high importance": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.482
                    }
                  },
                  {
                    "guge high significance": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.482
                    }
                  },
                  {
                    "guge high usefulness": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.482
                    }
                  },
                  {
                    "guge high consequence": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.482
                    }
                  }
                ]
              },
              "v_Measures_measure.guge_minimum": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Measures",
                    "ConceptualProperty": "Guge minimum"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "guge minimum": {
                      "State": "Generated"
                    }
                  },
                  {
                    "guge iota": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.475
                    }
                  },
                  {
                    "guge modicum": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.475
                    }
                  },
                  {
                    "guge smidgeon": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.475
                    }
                  },
                  {
                    "guge smidgen": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.475
                    }
                  },
                  {
                    "guge least": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.461
                    }
                  },
                  {
                    "guge jot": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.461
                    }
                  },
                  {
                    "guge speck": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.461
                    }
                  }
                ]
              },
              "v_Measures_measure.icon": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Measures",
                    "ConceptualProperty": "Icon"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "icon": {
                      "State": "Generated"
                    }
                  },
                  {
                    "likeness": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "representation": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "portrait": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "emblem": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "logo": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "image": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "sign": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "photograph": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "drawing": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "picture": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  }
                ]
              },
              "v_Measures_measure.placement_total": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Measures",
                    "ConceptualProperty": "Placement Total"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "placement total": {
                      "State": "Generated"
                    }
                  },
                  {
                    "placement aggregate": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "placement overall": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "Order PL": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "v_Measures_measure.projection_total": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Measures",
                    "ConceptualProperty": "Projection Total"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "projection total": {
                      "State": "Generated"
                    }
                  },
                  {
                    "projection aggregate": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "projection overall": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "Order PJ": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "v_Measures_measure.rank": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Measures",
                    "ConceptualProperty": "Rank"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "rank": {
                      "State": "Generated"
                    }
                  },
                  {
                    "flourishing": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "sheer": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.452
                    }
                  },
                  {
                    "absolute": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.452
                    }
                  }
                ]
              },
              "v_Measures_measure.top_n_SUM": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Measures",
                    "ConceptualProperty": "Top N SUM"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "top n SUM": {
                      "State": "Generated"
                    }
                  },
                  {
                    "n SUM": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "top n summation": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.762
                    }
                  },
                  {
                    "top n aggregation": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.762
                    }
                  },
                  {
                    "n summation": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "n aggregation": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "top n total": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.739
                    }
                  },
                  {
                    "top n aggregate": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.739
                    }
                  },
                  {
                    "top n amount": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.739
                    }
                  },
                  {
                    "n total": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "n aggregate": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "n amount": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  }
                ]
              },
              "v_Measures_measure.top_n_sum_placement_by_brand": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Measures",
                    "ConceptualProperty": "Top N Sum Placement by Brand"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "top n sum placement by brand": {
                      "State": "Generated"
                    }
                  },
                  {
                    "sum placement": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "n sum placement": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "top n sum placement": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "top n summation placement": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.617
                    }
                  },
                  {
                    "top n aggregation placement": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.617
                    }
                  },
                  {
                    "n summation placement": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.609
                    }
                  },
                  {
                    "n aggregation placement": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.609
                    }
                  },
                  {
                    "summation placement": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "aggregation placement": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "best n sum placement": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.599
                    }
                  },
                  {
                    "first n sum placement": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.599
                    }
                  },
                  {
                    "leading n sum placement": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.599
                    }
                  },
                  {
                    "maximum n sum placement": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.599
                    }
                  }
                ]
              },
              "v_Measures_measure.top_n_sum_sales_customers": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Measures",
                    "ConceptualProperty": "Top N Sum Sales Customers"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "top n sum sales customers": {
                      "State": "Generated"
                    }
                  },
                  {
                    "customers": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "sales customers": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "sum sales customers": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "n sum sales customers": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "top n summation sale customer": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.624
                    }
                  },
                  {
                    "top n aggregation sale customer": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.624
                    }
                  },
                  {
                    "n summation sale customer": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.617
                    }
                  },
                  {
                    "n aggregation sale customer": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.617
                    }
                  },
                  {
                    "summation sale customer": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.609
                    }
                  },
                  {
                    "aggregation sale customer": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.609
                    }
                  },
                  {
                    "best n sum sale customer": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.605
                    }
                  },
                  {
                    "first n sum sale customer": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.605
                    }
                  },
                  {
                    "leading n sum sale customer": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.605
                    }
                  },
                  {
                    "maximum n sum sale customer": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.605
                    }
                  }
                ]
              },
              "v_Measures_measure.v_Placement_Total_FormatString_placement_total_FormatString": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Measures",
                    "ConceptualProperty": "_Placement Total FormatString"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "_placement total FormatString": {
                      "State": "Generated"
                    }
                  },
                  {
                    "_placement aggregate formatstring": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.599
                    }
                  },
                  {
                    "_placement overall formatstring": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.599
                    }
                  }
                ],
                "Visibility": {
                  "Value": "Hidden"
                }
              },
              "v_Measures_measure.v_Projection_Total_FormatString_projection_total_FormatString": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Measures",
                    "ConceptualProperty": "_Projection Total FormatString"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "_projection total FormatString": {
                      "State": "Generated"
                    }
                  },
                  {
                    "_projection aggregate formatstring": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.599
                    }
                  },
                  {
                    "_projection overall formatstring": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.599
                    }
                  }
                ],
                "Visibility": {
                  "Value": "Hidden"
                }
              },
              "v_Measures_measure.v_Varience_FormatString_varience_FormatString": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Measures",
                    "ConceptualProperty": "_Varience FormatString"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "_varience FormatString": {
                      "State": "Generated"
                    }
                  }
                ],
                "Visibility": {
                  "Value": "Hidden"
                }
              },
              "v_Measures_measure.varience": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Measures",
                    "ConceptualProperty": "Varience"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "varience": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "v_Measures_measure.varience_": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Measures",
                    "ConceptualProperty": "Varience %"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "varience %": {
                      "State": "Generated"
                    }
                  },
                  {
                    "varience percentage": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "varience pct": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  }
                ]
              }
            },
            "Language": "en-US",
            "Relationships": {
              "dataset_has_dim_date": {
                "Binding": {
                  "ConceptualEntity": "Dataset"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "dim_date"
                      },
                      "Subject": {
                        "Role": "dataset"
                      }
                    },
                    "ID": "datasets_have_dim_dates",
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "dataset"
                      },
                      "Subject": {
                        "Role": "dim_date"
                      }
                    },
                    "ID": "dim_dates_have_datasets",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "dataset": {
                    "Target": {
                      "Entity": "dataset"
                    }
                  },
                  "dim_date": {
                    "Nouns": [
                      {
                        "month": {
                          "State": "Generated"
                        }
                      }
                    ],
                    "Target": {
                      "Entity": "dim_date"
                    }
                  }
                },
                "State": "Generated"
              },
              "dataset_has_month": {
                "Binding": {
                  "ConceptualEntity": "Dataset"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "dataset.month"
                      },
                      "Subject": {
                        "Role": "dataset"
                      }
                    },
                    "ID": "datasets_have_months",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "dataset": {
                    "Target": {
                      "Entity": "dataset"
                    }
                  },
                  "dataset.month": {
                    "Target": {
                      "Entity": "dataset.month"
                    }
                  }
                },
                "State": "Generated"
              },
              "dataset_has_placement": {
                "Binding": {
                  "ConceptualEntity": "Dataset"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "dataset.placement"
                      },
                      "Subject": {
                        "Role": "dataset"
                      }
                    },
                    "ID": "datasets_have_placements",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "dataset": {
                    "Target": {
                      "Entity": "dataset"
                    }
                  },
                  "dataset.placement": {
                    "Target": {
                      "Entity": "dataset.placement"
                    }
                  }
                },
                "State": "Generated"
              },
              "dataset_has_placement_bucket": {
                "Binding": {
                  "ConceptualEntity": "Dataset"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "dataset.placement_bucket"
                      },
                      "Subject": {
                        "Role": "dataset"
                      }
                    },
                    "ID": "datasets_have_placement_buckets",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "dataset": {
                    "Target": {
                      "Entity": "dataset"
                    }
                  },
                  "dataset.placement_bucket": {
                    "Target": {
                      "Entity": "dataset.placement_bucket"
                    }
                  }
                },
                "State": "Generated"
              },
              "dataset_has_projection": {
                "Binding": {
                  "ConceptualEntity": "Dataset"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "dataset.projection"
                      },
                      "Subject": {
                        "Role": "dataset"
                      }
                    },
                    "ID": "datasets_have_projections",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "dataset": {
                    "Target": {
                      "Entity": "dataset"
                    }
                  },
                  "dataset.projection": {
                    "Target": {
                      "Entity": "dataset.projection"
                    }
                  }
                },
                "State": "Generated"
              },
              "dataset_has_pseudo_prod_table": {
                "Binding": {
                  "ConceptualEntity": "Dataset"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "pseudo_prod_table"
                      },
                      "Subject": {
                        "Role": "dataset"
                      }
                    },
                    "ID": "datasets_have_pseudo_prod_tables",
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "dataset"
                      },
                      "Subject": {
                        "Role": "pseudo_prod_table"
                      }
                    },
                    "ID": "pseudo_prod_tables_have_datasets",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "dataset": {
                    "Target": {
                      "Entity": "dataset"
                    }
                  },
                  "pseudo_prod_table": {
                    "Target": {
                      "Entity": "pseudo_prod_table"
                    }
                  }
                },
                "State": "Generated"
              },
              "dataset_has_pseudo_prod_table_b": {
                "Binding": {
                  "ConceptualEntity": "Dataset"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "pseudo_prod_table_b"
                      },
                      "Subject": {
                        "Role": "dataset"
                      }
                    },
                    "ID": "datasets_have_pseudo_prod_table_b",
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "dataset"
                      },
                      "Subject": {
                        "Role": "pseudo_prod_table_b"
                      }
                    },
                    "ID": "pseudo_prod_table_b_have_datasets",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "dataset": {
                    "Target": {
                      "Entity": "dataset"
                    }
                  },
                  "pseudo_prod_table_b": {
                    "Target": {
                      "Entity": "pseudo_prod_table_b"
                    }
                  }
                },
                "State": "Generated"
              },
              "dataset_has_sl__no_": {
                "Binding": {
                  "ConceptualEntity": "Dataset"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "dataset.sl__no_"
                      },
                      "Subject": {
                        "Role": "dataset"
                      }
                    },
                    "ID": "datasets_have_sl__no_",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "dataset": {
                    "Target": {
                      "Entity": "dataset"
                    }
                  },
                  "dataset.sl__no_": {
                    "Target": {
                      "Entity": "dataset.sl__no_"
                    }
                  }
                },
                "State": "Generated"
              },
              "dataset_has_team_leader": {
                "Binding": {
                  "ConceptualEntity": "Dataset"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "dataset.team_leader"
                      },
                      "Subject": {
                        "Role": "dataset"
                      }
                    },
                    "ID": "datasets_have_team_leaders",
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "ID": "team_leaders_lead_datasets",
                    "State": "Generated",
                    "Verb": {
                      "Object": {
                        "Role": "dataset"
                      },
                      "Subject": {
                        "Role": "dataset.team_leader"
                      },
                      "Verbs": [
                        {
                          "lead": {
                            "State": "Generated"
                          }
                        }
                      ]
                    },
                    "Weight": 0.75
                  },
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "dataset"
                      },
                      "Subject": {
                        "Role": "dataset.team_leader"
                      }
                    },
                    "ID": "team_leaders_have_datasets",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "dataset": {
                    "Target": {
                      "Entity": "dataset"
                    }
                  },
                  "dataset.team_leader": {
                    "Target": {
                      "Entity": "dataset.team_leader"
                    }
                  }
                },
                "State": "Generated"
              },
              "dataset_has_v_Measures_measure_bar": {
                "Binding": {
                  "ConceptualEntity": "Dataset"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "v_Measures_measure.bar"
                      },
                      "Subject": {
                        "Role": "dataset"
                      }
                    },
                    "ID": "datasets_have_bar",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "dataset": {
                    "Target": {
                      "Entity": "dataset"
                    }
                  },
                  "v_Measures_measure.bar": {
                    "Target": {
                      "Entity": "v_Measures_measure.bar"
                    }
                  }
                },
                "State": "Generated"
              },
              "dataset_has_v_Measures_measure_guge_high_value": {
                "Binding": {
                  "ConceptualEntity": "Dataset"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "v_Measures_measure.guge_high_value"
                      },
                      "Subject": {
                        "Role": "dataset"
                      }
                    },
                    "ID": "datasets_have_guge_high_value",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "dataset": {
                    "Target": {
                      "Entity": "dataset"
                    }
                  },
                  "v_Measures_measure.guge_high_value": {
                    "Target": {
                      "Entity": "v_Measures_measure.guge_high_value"
                    }
                  }
                },
                "State": "Generated"
              },
              "dataset_has_v_Measures_measure_guge_minimum": {
                "Binding": {
                  "ConceptualEntity": "Dataset"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "v_Measures_measure.guge_minimum"
                      },
                      "Subject": {
                        "Role": "dataset"
                      }
                    },
                    "ID": "datasets_have_guge_minimum",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "dataset": {
                    "Target": {
                      "Entity": "dataset"
                    }
                  },
                  "v_Measures_measure.guge_minimum": {
                    "Target": {
                      "Entity": "v_Measures_measure.guge_minimum"
                    }
                  }
                },
                "State": "Generated"
              },
              "dataset_has_v_Measures_measure_placement_total": {
                "Binding": {
                  "ConceptualEntity": "Dataset"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "v_Measures_measure.placement_total"
                      },
                      "Subject": {
                        "Role": "dataset"
                      }
                    },
                    "ID": "datasets_have_placement_total",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "dataset": {
                    "Target": {
                      "Entity": "dataset"
                    }
                  },
                  "v_Measures_measure.placement_total": {
                    "Target": {
                      "Entity": "v_Measures_measure.placement_total"
                    }
                  }
                },
                "State": "Generated"
              },
              "dataset_has_v_Measures_measure_projection_total": {
                "Binding": {
                  "ConceptualEntity": "Dataset"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "v_Measures_measure.projection_total"
                      },
                      "Subject": {
                        "Role": "dataset"
                      }
                    },
                    "ID": "datasets_have_projection_total",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "dataset": {
                    "Target": {
                      "Entity": "dataset"
                    }
                  },
                  "v_Measures_measure.projection_total": {
                    "Target": {
                      "Entity": "v_Measures_measure.projection_total"
                    }
                  }
                },
                "State": "Generated"
              },
              "dataset_has_v_Measures_measure_varience": {
                "Binding": {
                  "ConceptualEntity": "Dataset"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "v_Measures_measure.varience"
                      },
                      "Subject": {
                        "Role": "dataset"
                      }
                    },
                    "ID": "datasets_have_varience",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "dataset": {
                    "Target": {
                      "Entity": "dataset"
                    }
                  },
                  "v_Measures_measure.varience": {
                    "Target": {
                      "Entity": "v_Measures_measure.varience"
                    }
                  }
                },
                "State": "Generated"
              },
              "dataset_has_v_Measures_measure_varience_": {
                "Binding": {
                  "ConceptualEntity": "Dataset"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "v_Measures_measure.varience_"
                      },
                      "Subject": {
                        "Role": "dataset"
                      }
                    },
                    "ID": "datasets_have_varience_",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "dataset": {
                    "Target": {
                      "Entity": "dataset"
                    }
                  },
                  "v_Measures_measure.varience_": {
                    "Target": {
                      "Entity": "v_Measures_measure.varience_"
                    }
                  }
                },
                "State": "Generated"
              },
              "dim_date_has_date": {
                "Binding": {
                  "ConceptualEntity": "DimDate"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "dim_date.date"
                      },
                      "Subject": {
                        "Role": "dim_date"
                      }
                    },
                    "ID": "dim_dates_have_dates",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "dim_date": {
                    "Target": {
                      "Entity": "dim_date"
                    }
                  },
                  "dim_date.date": {
                    "Target": {
                      "Entity": "dim_date.date"
                    }
                  }
                },
                "State": "Generated"
              },
              "dim_date_has_month": {
                "Binding": {
                  "ConceptualEntity": "DimDate"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "dim_date.month"
                      },
                      "Subject": {
                        "Role": "dim_date"
                      }
                    },
                    "ID": "dim_dates_have_months",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "dim_date": {
                    "Target": {
                      "Entity": "dim_date"
                    }
                  },
                  "dim_date.month": {
                    "Target": {
                      "Entity": "dim_date.month"
                    }
                  }
                },
                "State": "Generated"
              },
              "dim_date_has_month_name": {
                "Binding": {
                  "ConceptualEntity": "DimDate"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "dim_date.month_name"
                      },
                      "Subject": {
                        "Role": "dim_date"
                      }
                    },
                    "ID": "dim_dates_have_month_names",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "dim_date": {
                    "Target": {
                      "Entity": "dim_date"
                    }
                  },
                  "dim_date.month_name": {
                    "Target": {
                      "Entity": "dim_date.month_name"
                    }
                  }
                },
                "State": "Generated"
              },
              "dim_date_has_quarter": {
                "Binding": {
                  "ConceptualEntity": "DimDate"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "dim_date.quarter"
                      },
                      "Subject": {
                        "Role": "dim_date"
                      }
                    },
                    "ID": "dim_dates_have_quarters",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "dim_date": {
                    "Target": {
                      "Entity": "dim_date"
                    }
                  },
                  "dim_date.quarter": {
                    "Target": {
                      "Entity": "dim_date.quarter"
                    }
                  }
                },
                "State": "Generated"
              },
              "dim_date_has_quarter_name": {
                "Binding": {
                  "ConceptualEntity": "DimDate"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "dim_date.quarter_name"
                      },
                      "Subject": {
                        "Role": "dim_date"
                      }
                    },
                    "ID": "dim_dates_have_quarter_names",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "dim_date": {
                    "Target": {
                      "Entity": "dim_date"
                    }
                  },
                  "dim_date.quarter_name": {
                    "Target": {
                      "Entity": "dim_date.quarter_name"
                    }
                  }
                },
                "State": "Generated"
              },
              "dim_date_has_week_name": {
                "Binding": {
                  "ConceptualEntity": "DimDate"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "dim_date.week_name"
                      },
                      "Subject": {
                        "Role": "dim_date"
                      }
                    },
                    "ID": "dim_dates_have_week_names",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "dim_date": {
                    "Target": {
                      "Entity": "dim_date"
                    }
                  },
                  "dim_date.week_name": {
                    "Target": {
                      "Entity": "dim_date.week_name"
                    }
                  }
                },
                "State": "Generated"
              },
              "dim_date_has_week_of_year": {
                "Binding": {
                  "ConceptualEntity": "DimDate"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "dim_date.week_of_year"
                      },
                      "Subject": {
                        "Role": "dim_date"
                      }
                    },
                    "ID": "dim_dates_have_week_of_year",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "dim_date": {
                    "Target": {
                      "Entity": "dim_date"
                    }
                  },
                  "dim_date.week_of_year": {
                    "Target": {
                      "Entity": "dim_date.week_of_year"
                    }
                  }
                },
                "State": "Generated"
              },
              "dim_date_has_year": {
                "Binding": {
                  "ConceptualEntity": "DimDate"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "dim_date.year"
                      },
                      "Subject": {
                        "Role": "dim_date"
                      }
                    },
                    "ID": "dim_dates_have_years",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "dim_date": {
                    "Target": {
                      "Entity": "dim_date"
                    }
                  },
                  "dim_date.year": {
                    "Target": {
                      "Entity": "dim_date.year"
                    }
                  }
                },
                "State": "Generated"
              },
              "parameter_has_parameter": {
                "Binding": {
                  "ConceptualEntity": "Parameter"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "parameter.parameter"
                      },
                      "Subject": {
                        "Role": "parameter"
                      }
                    },
                    "ID": "parameters_have_parameters",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "parameter": {
                    "Target": {
                      "Entity": "parameter"
                    }
                  },
                  "parameter.parameter": {
                    "Target": {
                      "Entity": "parameter.parameter"
                    }
                  }
                },
                "State": "Generated"
              },
              "parameter_has_parameter_value": {
                "Binding": {
                  "ConceptualEntity": "Parameter"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "parameter.parameter_value"
                      },
                      "Subject": {
                        "Role": "parameter"
                      }
                    },
                    "ID": "parameters_have_parameter_value",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "parameter": {
                    "Target": {
                      "Entity": "parameter"
                    }
                  },
                  "parameter.parameter_value": {
                    "Target": {
                      "Entity": "parameter.parameter_value"
                    }
                  }
                },
                "State": "Generated"
              },
              "pseudo_prod_table_b_has_brand": {
                "Binding": {
                  "ConceptualEntity": "Pseudo Prod Table B"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "pseudo_prod_table_b.brand"
                      },
                      "Subject": {
                        "Role": "pseudo_prod_table_b"
                      }
                    },
                    "ID": "pseudo_prod_table_b_have_brands",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "pseudo_prod_table_b": {
                    "Target": {
                      "Entity": "pseudo_prod_table_b"
                    }
                  },
                  "pseudo_prod_table_b.brand": {
                    "Target": {
                      "Entity": "pseudo_prod_table_b.brand"
                    }
                  }
                },
                "State": "Generated"
              },
              "pseudo_prod_table_has_brand": {
                "Binding": {
                  "ConceptualEntity": "Pseudo Prod Table"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "pseudo_prod_table.brand"
                      },
                      "Subject": {
                        "Role": "pseudo_prod_table"
                      }
                    },
                    "ID": "pseudo_prod_tables_have_brands",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "pseudo_prod_table": {
                    "Target": {
                      "Entity": "pseudo_prod_table"
                    }
                  },
                  "pseudo_prod_table.brand": {
                    "Target": {
                      "Entity": "pseudo_prod_table.brand"
                    }
                  }
                },
                "State": "Generated"
              },
              "v_Measures_measure_has_bar_chart_detail": {
                "Binding": {
                  "ConceptualEntity": "_Measures"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "v_Measures_measure.bar_chart_detail"
                      },
                      "Subject": {
                        "Role": "v_Measures_measure"
                      }
                    },
                    "ID": "Phrasing_measures_have_bar_chart_detail",
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "ID": "Phrasing_measures_are_bar_bar_chart_detail",
                    "Preposition": {
                      "Object": {
                        "Role": "v_Measures_measure.bar_chart_detail"
                      },
                      "Prepositions": [
                        {
                          "bar": {
                            "State": "Generated"
                          }
                        }
                      ],
                      "Subject": {
                        "Role": "v_Measures_measure"
                      }
                    },
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "v_Measures_measure": {
                    "Target": {
                      "Entity": "v_Measures_measure"
                    }
                  },
                  "v_Measures_measure.bar_chart_detail": {
                    "Target": {
                      "Entity": "v_Measures_measure.bar_chart_detail"
                    }
                  }
                },
                "State": "Generated"
              },
              "v_Measures_measure_has_bottom_brands_placement": {
                "Binding": {
                  "ConceptualEntity": "_Measures"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "v_Measures_measure.bottom_brands_placement"
                      },
                      "Subject": {
                        "Role": "v_Measures_measure"
                      }
                    },
                    "ID": "Phrasing_measures_have_bottom_brands_placement",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "v_Measures_measure": {
                    "Target": {
                      "Entity": "v_Measures_measure"
                    }
                  },
                  "v_Measures_measure.bottom_brands_placement": {
                    "Target": {
                      "Entity": "v_Measures_measure.bottom_brands_placement"
                    }
                  }
                },
                "State": "Generated"
              },
              "v_Measures_measure_has_bottom_brands_total": {
                "Binding": {
                  "ConceptualEntity": "_Measures"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "v_Measures_measure.bottom_brands_total"
                      },
                      "Subject": {
                        "Role": "v_Measures_measure"
                      }
                    },
                    "ID": "Phrasing_measures_have_bottom_brands_total",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "v_Measures_measure": {
                    "Target": {
                      "Entity": "v_Measures_measure"
                    }
                  },
                  "v_Measures_measure.bottom_brands_total": {
                    "Target": {
                      "Entity": "v_Measures_measure.bottom_brands_total"
                    }
                  }
                },
                "State": "Generated"
              },
              "v_Measures_measure_has_customer_rank": {
                "Binding": {
                  "ConceptualEntity": "_Measures"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "v_Measures_measure.customer_rank"
                      },
                      "Subject": {
                        "Role": "v_Measures_measure"
                      }
                    },
                    "ID": "Phrasing_measures_have_customer_rank",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "v_Measures_measure": {
                    "Target": {
                      "Entity": "v_Measures_measure"
                    }
                  },
                  "v_Measures_measure.customer_rank": {
                    "Target": {
                      "Entity": "v_Measures_measure.customer_rank"
                    }
                  }
                },
                "State": "Generated"
              },
              "v_Measures_measure_has_customers_top_n_sum": {
                "Binding": {
                  "ConceptualEntity": "_Measures"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "v_Measures_measure.customers_top_n_sum"
                      },
                      "Subject": {
                        "Role": "v_Measures_measure"
                      }
                    },
                    "ID": "Phrasing_measures_have_customers_top_n_sum",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "v_Measures_measure": {
                    "Target": {
                      "Entity": "v_Measures_measure"
                    }
                  },
                  "v_Measures_measure.customers_top_n_sum": {
                    "Target": {
                      "Entity": "v_Measures_measure.customers_top_n_sum"
                    }
                  }
                },
                "State": "Generated"
              },
              "v_Measures_measure_has_icon": {
                "Binding": {
                  "ConceptualEntity": "_Measures"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "v_Measures_measure.icon"
                      },
                      "Subject": {
                        "Role": "v_Measures_measure"
                      }
                    },
                    "ID": "Phrasing_measures_have_icon",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "v_Measures_measure": {
                    "Target": {
                      "Entity": "v_Measures_measure"
                    }
                  },
                  "v_Measures_measure.icon": {
                    "Target": {
                      "Entity": "v_Measures_measure.icon"
                    }
                  }
                },
                "State": "Generated"
              },
              "v_Measures_measure_has_rank": {
                "Binding": {
                  "ConceptualEntity": "_Measures"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "v_Measures_measure.rank"
                      },
                      "Subject": {
                        "Role": "v_Measures_measure"
                      }
                    },
                    "ID": "Phrasing_measures_have_rank",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "v_Measures_measure": {
                    "Target": {
                      "Entity": "v_Measures_measure"
                    }
                  },
                  "v_Measures_measure.rank": {
                    "Target": {
                      "Entity": "v_Measures_measure.rank"
                    }
                  }
                },
                "State": "Generated"
              },
              "v_Measures_measure_has_top_n_SUM": {
                "Binding": {
                  "ConceptualEntity": "_Measures"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "v_Measures_measure.top_n_SUM"
                      },
                      "Subject": {
                        "Role": "v_Measures_measure"
                      }
                    },
                    "ID": "Phrasing_measures_have_top_n_SUM",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "v_Measures_measure": {
                    "Target": {
                      "Entity": "v_Measures_measure"
                    }
                  },
                  "v_Measures_measure.top_n_SUM": {
                    "Target": {
                      "Entity": "v_Measures_measure.top_n_SUM"
                    }
                  }
                },
                "State": "Generated"
              },
              "v_Measures_measure_has_top_n_sum_placement_by_brand": {
                "Binding": {
                  "ConceptualEntity": "_Measures"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "v_Measures_measure.top_n_sum_placement_by_brand"
                      },
                      "Subject": {
                        "Role": "v_Measures_measure"
                      }
                    },
                    "ID": "Phrasing_measures_have_top_n_sum_placement_by_brand",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "v_Measures_measure": {
                    "Target": {
                      "Entity": "v_Measures_measure"
                    }
                  },
                  "v_Measures_measure.top_n_sum_placement_by_brand": {
                    "Target": {
                      "Entity": "v_Measures_measure.top_n_sum_placement_by_brand"
                    }
                  }
                },
                "State": "Generated"
              },
              "v_Measures_measure_has_top_n_sum_sales_customers": {
                "Binding": {
                  "ConceptualEntity": "_Measures"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "v_Measures_measure.top_n_sum_sales_customers"
                      },
                      "Subject": {
                        "Role": "v_Measures_measure"
                      }
                    },
                    "ID": "Phrasing_measures_have_top_n_sum_sales_customers",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "v_Measures_measure": {
                    "Target": {
                      "Entity": "v_Measures_measure"
                    }
                  },
                  "v_Measures_measure.top_n_sum_sales_customers": {
                    "Target": {
                      "Entity": "v_Measures_measure.top_n_sum_sales_customers"
                    }
                  }
                },
                "State": "Generated"
              }
            },
            "Version": "3.5.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "StartDate",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Date"
          }
        ],
        "expression": [
          "let",
          "    Source = #date(2024, 1, 1)",
          "in",
          "    Source"
        ],
        "kind": "m",
        "lineageTag": "4f2ab737-d468-43f7-8a93-3de7df0da518"
      },
      {
        "name": "EndDate",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Date"
          }
        ],
        "expression": [
          "let",
          "    Source = #date(2024, 12, 31)",
          "in",
          "    Source"
        ],
        "kind": "m",
        "lineageTag": "6da3bea7-229d-4b79-b250-ffbc8e5448fc"
      }
    ],
    "relationships": [
      {
        "name": "20d0d241-4e70-a2ac-db48-79953f962054",
        "fromColumn": "Month",
        "fromTable": "Dataset",
        "toColumn": "Dates",
        "toTable": "DimDate"
      },
      {
        "name": "7d7521a9-2b4e-5e8f-9cd8-84bd647ff00c",
        "fromColumn": "Brand",
        "fromTable": "Dataset",
        "toColumn": "Brand",
        "toTable": "Pseudo Prod Table"
      },
      {
        "name": "fafcb251-eb46-628a-de30-eac04ae14c5d",
        "fromColumn": "Brands",
        "fromTable": "Dataset",
        "toColumn": "Brands",
        "toTable": "Pseudo Prod Table B"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "Dataset",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Sl. No.",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "62eeb70f-3fce-4e6a-afed-a857356e6c5d",
            "sourceColumn": "Sl. No.",
            "summarizeBy": "sum"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "aab310be-6eb6-43e7-9e41-77093fe2180a",
            "sourceColumn": "Month",
            "summarizeBy": "none"
          },
          {
            "name": "Team Leader",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dbf51fa5-1c27-4c5a-adb5-88bbe777cd6f",
            "sourceColumn": "Team Leader",
            "summarizeBy": "none"
          },
          {
            "name": "Brands",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "73b13de6-7e20-4e35-a633-b102564f32a0",
            "sourceColumn": "Brands",
            "summarizeBy": "none"
          },
          {
            "name": "Projection",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "5650811c-3c0a-4b67-9477-a87a7634e008",
            "sourceColumn": "Projection",
            "summarizeBy": "sum"
          },
          {
            "name": "Placement",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "fe15d2bb-d73e-488c-810a-9a6fa8dc78be",
            "sourceColumn": "Placement",
            "summarizeBy": "sum"
          },
          {
            "name": "Brand",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5a8fab2c-934c-4fb4-8b93-9cc1ce618f0f",
            "sourceColumn": "Brand",
            "summarizeBy": "none"
          },
          {
            "name": "Placement_Bucket",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b4650b1b-4921-4ea7-890d-af1bffd3a6f4",
            "sourceColumn": "Placement_Bucket",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "f2b929f6-1089-4854-a7b2-3408bb17a8a9",
        "partitions": [
          {
            "name": "Dataset",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"H:\\_Portfolio Project Github\\FMGC Analysis\\Data Set.xlsx\"), null, true),",
                "    Dataset_Sheet = Source{[Item=\"Dataset\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Dataset_Sheet, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Sl. No.\", Int64.Type}, {\"Month\", type date}, {\"Team Leader\", type text}, {\"Brands\", type text}, {\"Projection\", type number}, {\"Placement\", type number}, {\"Brand\", type text}}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Changed Type\", \"Placement_Bucket\", each if [Placement] <= 20000 then \"Low\"",
                "else if [Placement] <= 50000 then \"Medium\"",
                "else \"High\"),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Added Custom\",{{\"Month\", type date}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type1\",{\"Column10\", \"Column8\", \"Column9\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DimDate",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Dates",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "isKey": true,
            "lineageTag": "f6aa1353-b4b7-44ea-9efb-c45b55b634fa",
            "sourceColumn": "Dates",
            "summarizeBy": "none"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1eaa69be-5d9d-4973-a10f-6753fbcbb40c",
            "sourceColumn": "Year",
            "summarizeBy": "none"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b9dcfade-9aa2-4cd8-9974-6783209e67a1",
            "sourceColumn": "Month",
            "summarizeBy": "none"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "373a65ed-5e1d-43f6-b431-80d813daa188",
            "sourceColumn": "Quarter",
            "summarizeBy": "none"
          },
          {
            "name": "Week of Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4e29bb20-22ff-40d9-a71f-24a3aaf61b40",
            "sourceColumn": "Week of Year",
            "summarizeBy": "none"
          },
          {
            "name": "Month Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "b2860d3e-410e-4a31-b9d7-224b392b5535",
            "sortByColumn": "Month",
            "sourceColumn": "Month Name",
            "summarizeBy": "none"
          },
          {
            "name": "Quarter Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "3a67a683-d837-4edd-85f2-cc4354fc0ea9",
            "sortByColumn": "Quarter",
            "sourceColumn": "Quarter Name",
            "summarizeBy": "none"
          },
          {
            "name": "Week Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "0cd8df75-2006-4a6a-b816-c592db1d7e66",
            "sortByColumn": "Week of Year",
            "sourceColumn": "Week Name",
            "summarizeBy": "none"
          }
        ],
        "dataCategory": "Time",
        "lineageTag": "d0aff1a3-b3df-4323-93dc-f834750f7281",
        "partitions": [
          {
            "name": "DimDate",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Duration = Duration.Days(EndDate-StartDate)+1,",
                "    #\"List of date\" = List.Dates(StartDate, Duration, #duration(1,0,0,0)),",
                "    #\"Converted to Table\" = Table.FromList(#\"List of date\", Splitter.SplitByNothing(), null, null, ExtraValues.Error),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Converted to Table\",{{\"Column1\", \"Dates\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"Dates\", type date}}),",
                "    #\"Inserted Year\" = Table.AddColumn(#\"Changed Type\", \"Year\", each Date.Year([Dates]), Int64.Type),",
                "    #\"Inserted Month\" = Table.AddColumn(#\"Inserted Year\", \"Month\", each Date.Month([Dates]), Int64.Type),",
                "    #\"Inserted Quarter\" = Table.AddColumn(#\"Inserted Month\", \"Quarter\", each Date.QuarterOfYear([Dates]), Int64.Type),",
                "    #\"Inserted Week of Year\" = Table.AddColumn(#\"Inserted Quarter\", \"Week of Year\", each Date.WeekOfYear([Dates]), Int64.Type),",
                "    #\"Inserted Month Name\" = Table.AddColumn(#\"Inserted Week of Year\", \"Month Name\", each Date.MonthName([Dates]), type text),",
                "    #\"Extracted First Characters\" = Table.TransformColumns(#\"Inserted Month Name\", {{\"Month Name\", each Text.Start(_, 3), type text}}),",
                "    #\"Added Quarter Name\" = Table.AddColumn(#\"Extracted First Characters\", \"Quarter Name\", each \"Q\"& Text.From([Quarter])),",
                "    #\"Added Week Name\" = Table.AddColumn(#\"Added Quarter Name\", \"Week Name\", each \"W\"& Text.From([Week of Year]))",
                "in",
                "    #\"Added Week Name\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "_Measures",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "lineageTag": "68fa9b2b-7cba-4ff7-a61c-012435da031d",
        "measures": [
          {
            "name": "Placement Total",
            "expression": "SUM('Dataset'[Placement])",
            "formatStringDefinition": {
              "expression": [
                "SWITCH(",
                "    TRUE(),",
                "    SELECTEDMEASURE() > 1000000, \"#,##0,,.00M\",",
                "    SELECTEDMEASURE() > 1000, \"#,##0,.00K\"",
                ")"
              ]
            },
            "lineageTag": "321d0248-4fb8-4b45-899c-20c44831e1c6"
          },
          {
            "name": "Projection Total",
            "expression": "SUM('Dataset'[Projection])",
            "formatStringDefinition": {
              "expression": [
                "SWITCH(",
                "    TRUE(),",
                "    SELECTEDMEASURE() > 1000000, \"#,##0,,.00M\",",
                "    SELECTEDMEASURE() > 1000, \"#,##0,.00K\"",
                ")"
              ]
            },
            "lineageTag": "3fe0e8e7-8b79-489b-bf07-ab53fa183be9"
          },
          {
            "name": "Varience",
            "expression": "[Placement Total] - [Projection Total]",
            "formatStringDefinition": {
              "expression": [
                "SWITCH(",
                "    TRUE(),",
                "    SELECTEDMEASURE() > 1000, \"#,##0,.0K\"",
                ")"
              ]
            },
            "lineageTag": "5da0d5ed-42cd-4fe7-8558-d99dc3f8bb26"
          },
          {
            "name": "Bar",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": "[Placement Total] - [Projection Total]",
            "formatString": "0",
            "lineageTag": "76b91753-c841-44e4-93ba-70ff483edbb9"
          },
          {
            "name": "Icon",
            "expression": [
              "",
              "VAR varinece = [Varience]",
              "VAR icon = SWITCH(",
              "    TRUE(),",
              "    varinece < 0, \"\"",
              ")",
              "VAR Varience_pct = [Varience %]",
              "VAR result =  FORMAT(Varience_pct, \"0.##%\") & \" \" & icon",
              "RETURN",
              "result"
            ],
            "lineageTag": "418c0d00-e787-4a33-bf3e-a91084612b70"
          },
          {
            "name": "Guge High Value",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "[Projection Total] * 1.15",
            "lineageTag": "d7425624-091b-4129-8fa2-fc48a5a2bc93"
          },
          {
            "name": "Guge minimum",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "[Projection Total]*.7",
            "lineageTag": "f3fcda49-aadb-4fa5-9882-707b2c935eb6"
          },
          {
            "name": "Top N Sum Placement by Brand",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Brand Top",
            "expression": [
              "",
              "VAR TopNSelected =                              -- capturing top value selected in the slicer",
              "    SELECTEDVALUE ( Parameter[Parameter] )",
              "VAR TopProdTable =",
              "    TOPN (",
              "        TopNSelected,",
              "        ALLSELECTED ( 'Pseudo Prod Table' ),",
              "        [Placement Total]",
              "    )",
              "VAR TopProdSales =",
              "    CALCULATE (",
              "        [Placement Total],",
              "        KEEPFILTERS ( TopProdTable )",
              "    )",
              "VAR OtherSales =",
              "    CALCULATE (",
              "        [Placement Total],",
              "        ALLSELECTED ( 'Pseudo Prod Table' )",
              "    )",
              "        - CALCULATE (",
              "            [Placement Total],",
              "            TopProdTable",
              "        )",
              "VAR CurrentProd =",
              "    SELECTEDVALUE ( 'Pseudo Prod Table'[Brand] )",
              "RETURN",
              "    IF (",
              "        CurrentProd <> \"Others\",",
              "        TopProdSales,",
              "        OtherSales",
              "    )"
            ],
            "lineageTag": "840207f8-2930-49b2-97a2-2793744b4b9c"
          },
          {
            "name": "Rank",
            "displayFolder": "Brand Top",
            "expression": [
              "",
              "IF (",
              "    [Top N SUM]",
              "        <> BLANK (),",
              "    RANKX (",
              "        TOPN (                                         ",
              "            SELECTEDVALUE ( Parameter[Parameter] ),",
              "            ALLSELECTED ( 'Pseudo Prod Table' ),",
              "            [Placement Total]",
              "        ),",
              "        [Placement Total],       ",
              "        ,",
              "        DESC,",
              "        DENSE",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "64ca28b5-4905-43d8-879c-15b37e05c904"
          },
          {
            "name": "Top N SUM",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Brand Top",
            "expression": [
              "",
              "VAR TOPNSelected = SELECTEDVALUE(Parameter[Parameter])",
              "VAR CurrentProd = SELECTEDVALUE('Pseudo Prod Table'[Brand])",
              "VAR TopProducts = ",
              "    TOPN(",
              "        TopNSelected,",
              "        ALLSELECTED('Pseudo Prod Table'[Brand]),",
              "        [Placement Total]",
              "    )",
              "VAR TopProdSales = ",
              "    CALCULATE(",
              "        [Placement Total],",
              "        KEEPFILTERS( TopProducts )",
              "    )",
              "RETURN",
              "    SWITCH(",
              "        TRUE(),",
              "        CurrentProd <> \"Others\",",
              "        TopProdSales,",
              "        CurrentProd = \"Others\",",
              "            CALCULATE(",
              "                [Placement Total],",
              "                ALLSELECTED('Pseudo Prod Table'[Brand])",
              "            ) - ",
              "            CALCULATE(",
              "                [Placement Total], ",
              "                TopProducts",
              "            )",
              "    )"
            ],
            "lineageTag": "6b27b726-8c26-472c-9e0f-3cb439511072"
          },
          {
            "name": "Top N Sum Sales Customers",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "VAR TopNSelected =                              -- capturing top value selected in the slicer",
              "    SELECTEDVALUE ( Parameter[Parameter] )",
              "VAR TopProdTable =",
              "    TOPN (",
              "        TopNSelected,",
              "        ALLSELECTED ( 'Pseudo Prod Table B' ),",
              "        [Placement Total]",
              "    )",
              "VAR TopProdSales =",
              "    CALCULATE (",
              "        [Placement Total],",
              "        KEEPFILTERS ( TopProdTable )",
              "    )",
              "VAR OtherSales =",
              "    CALCULATE (",
              "        [Placement Total],",
              "        ALLSELECTED ( 'Pseudo Prod Table B' )",
              "    )",
              "        - CALCULATE (",
              "            [Placement Total],",
              "            TopProdTable",
              "        )",
              "VAR CurrentProd =",
              "    SELECTEDVALUE ( 'Pseudo Prod Table B'[Brands] )",
              "RETURN",
              "    IF (",
              "        CurrentProd <> \"Others\",",
              "        TopProdSales,",
              "        OtherSales",
              "    )",
              ""
            ],
            "lineageTag": "a581445d-d340-4a00-8ccc-403618c5360f"
          },
          {
            "name": "Customers top N Sum",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "VAR TOPNSelected = SELECTEDVALUE(Parameter[Parameter])",
              "VAR CurrentProd = SELECTEDVALUE('Pseudo Prod Table B'[Brands])",
              "VAR TopProducts = ",
              "    TOPN(",
              "        TopNSelected,",
              "        ALLSELECTED('Pseudo Prod Table B'[Brands]),",
              "        [Placement Total]",
              "    )",
              "VAR TopProdSales = ",
              "    CALCULATE(",
              "        [Placement Total],",
              "        KEEPFILTERS( TopProducts )",
              "    )",
              "RETURN",
              "    SWITCH(",
              "        TRUE(),",
              "        CurrentProd <> \"Others\",",
              "        TopProdSales,",
              "        CurrentProd = \"Others\",",
              "            CALCULATE(",
              "                [Placement Total],",
              "                ALLSELECTED('Pseudo Prod Table B'[Brands])",
              "            ) - ",
              "            CALCULATE(",
              "                [Placement Total], ",
              "                TopProducts",
              "            )",
              "    )"
            ],
            "lineageTag": "03f16a4c-ba89-419f-aa23-e19d968927e1"
          },
          {
            "name": "Customer Rank",
            "expression": [
              "",
              "IF (",
              "    [Customers top N Sum]",
              "        <> BLANK (),",
              "    RANKX (",
              "        TOPN (                                         ",
              "            SELECTEDVALUE ( Parameter[Parameter] ),",
              "            ALLSELECTED ( 'Pseudo Prod Table B' ),",
              "            [Placement Total]",
              "        ),",
              "        [Placement Total],       ",
              "        ,",
              "        DESC,",
              "        DENSE",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "2b09ec38-8066-4e05-836a-acd823b1f360"
          },
          {
            "name": "Bottom Brands Placement",
            "expression": "IF(RANKX(ALL('Dataset'[Brands]), [Placement Total],,ASC) <= Parameter[Parameter Value], [Placement Total], BLANK())",
            "formatString": "0",
            "lineageTag": "e9eaf9ca-868f-4c50-9f67-6d791b92d5ba"
          },
          {
            "name": "Bottom Brands Total",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "SUMX(TOPN(Parameter[Parameter Value], 'Dataset', [Placement Total], DESC), SUM('Dataset'[Placement]))",
            "lineageTag": "70805818-79bd-414d-9d73-9ffaaa7cfa88"
          },
          {
            "name": "Varience %",
            "expression": "DIVIDE(([Placement Total] - [Projection Total]), [Projection Total])",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "2eda3b18-3272-40e0-848f-d109b06a0675"
          },
          {
            "name": "Bar Chart Detail",
            "expression": [
              "",
              "VAR Varience = [Varience]",
              "VAR Result_1 = IF(Varience>=0, \"Achive \" , \"Diff: \")",
              "RETURN",
              "Result_1 & FORMAT(Varience, \"#,##0,.0K\")"
            ],
            "lineageTag": "fcaf0e7e-3d5a-4380-8457-8e50183f12f9"
          }
        ],
        "partitions": [
          {
            "name": "_Measures",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column1\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Pseudo Prod Table",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "559a4260f8fa450e95a8257faefbe9f0"
          }
        ],
        "columns": [
          {
            "name": "Brand",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "0e8fb294-7c58-4e13-9278-ae28a772bdeb",
            "sourceColumn": "Dataset[Brand]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "61cd9141-ba9c-4739-b531-7e816e3a0cd2",
        "partitions": [
          {
            "name": "Pseudo Prod Table",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "UNION(",
                "    DISTINCT('Dataset'[Brand]),",
                "    DATATABLE(",
                "        \"Brand\", STRING,",
                "        { {\"Others\"} }",
                "    )",
                ")",
                ""
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Parameter",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "877be4d35b5347b0a8545eeecfcf6396"
          }
        ],
        "columns": [
          {
            "name": "Parameter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "version": 0
                }
              }
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "18ab83f4-57d2-44e4-9932-dc01bb904bac",
            "sourceColumn": "[Value]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "295c64e4-78bf-453c-868a-2f656368db07",
        "measures": [
          {
            "name": "Parameter Value",
            "expression": "SELECTEDVALUE('Parameter'[Parameter], 1)",
            "formatString": "0",
            "lineageTag": "e3f5f40e-5855-4cb6-87eb-f50099c78329"
          }
        ],
        "partitions": [
          {
            "name": "Parameter",
            "mode": "import",
            "source": {
              "expression": "GENERATESERIES(0, 7, 1)",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Pseudo Prod Table B",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "c988233e379342d6975f4698533c577f"
          }
        ],
        "columns": [
          {
            "name": "Brands",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "ba91eb96-4930-4049-b680-58885b786e68",
            "sourceColumn": "Dataset[Brands]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "028e3412-7779-4115-ac73-2c731c26d35a",
        "partitions": [
          {
            "name": "Pseudo Prod Table B",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "UNION(",
                "    DISTINCT('Dataset'[Brands]),",
                "    DATATABLE(",
                "        \"Brands\", STRING,",
                "        { {\"Others\"} }",
                "    )",
                ")"
              ],
              "type": "calculated"
            }
          }
        ]
      }
    ]
  }
}